version: '3'

services:
  web-daily-puller:
    container_name: stevia-daily-puller
    image: alpine/git:latest
    restart: unless-stopped
    environment:
      TZ: "Asia/Jakarta"
      TARGET: "https://github.com/doscom-2018/doscom-2018.github.io"
      WAITTIME: "86400"
    entrypoint: ["/bin/sh","-c"]
    command: >
      "if [ ! -d /git/.git ]; then
        git clone $${TARGET} /git
      else
        git pull $${TARGET} master
      fi; sleep $${WAITTIME}"
    volumes:
      - ./home/:/root
      - ./www/:/git
  web-httpd-server:
    container_name: stevia-httpd-server
    build: .
    restart: unless-stopped
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - "8081:80"
    volumes:
      - ./www/:/usr/local/apache2/htdocs/
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/ || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s